test suite: introduced the support of seed values
The test script is modified to supply a test driver with
a random seed value and then compare the output of the reference
and testing programs. The test driver generates a test
from this value that makes it possible to test the reconstructed
program on different pseudorandom inputs.

diff --git a/test/do_test b/test/do_test
--- a/test/do_test
+++ b/test/do_test
@@ -1,11 +1,26 @@
-#!/bin/sh
+#!/bin/bash
 
 REFERENCE=$1
 TEST=$2
 
-echo "Executing the reference program..."
-./$REFERENCE
+if [ -z $LOOPS ]; then
+	LOOPS=1
+fi
 
-echo
-echo "Executung the reconstructed program..."
-./$TEST
+i=1
+
+while (( i <= LOOPS )); do
+	SEED=$RANDOM
+
+	echo "Doing loop" $i "with the seed" $SEED"..."
+	if diff <(./$REFERENCE $SEED) <(./$TEST $SEED); then
+		echo "OK"
+	else
+		echo "Fail"
+		exit 1
+	fi
+
+	i=$(( i + 1 ))
+done
+
+exit 0
